import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { FiCheck, FiX, FiRefreshCw, FiArrowLeft } from 'react-icons/fi';
import { toast } from 'react-toastify';
import api from '../../api/axiosConfig';

const QuestionReview = () => {
  const { assessmentId } = useParams();
  const navigate = useNavigate();
  const [questions, setQuestions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [reviewNotes, setReviewNotes] = useState('');
  const [rejectionReason, setRejectionReason] = useState('');

  useEffect(() => {
    loadPendingQuestions();
  }, [assessmentId]);

  const loadPendingQuestions = async () => {
    try {
      const response = await api.get(`/admin/questions/review/${assessmentId}`);
      if (response.data.data) {
        setQuestions(response.data.data);
        setLoading(false);
      }
    } catch (error) {
      console.error('Failed to load questions:', error);
      toast.error('Failed to load pending questions');
      setLoading(false);
    }
  };

  const handleApprove = async () => {
    try {
      const question = questions[currentIndex];
      await api.post(`/admin/questions/${question.id}/approve`, {
        notes: reviewNotes
      });
      toast.success('Question approved');
      handleNext();
    } catch (error) {
      toast.error('Failed to approve question');
    }
  };

  const handleReject = async () => {
    if (!rejectionReason.trim()) {
      toast.error('Please provide a reason for rejection');
      return;
    }
    try {
      const question = questions[currentIndex];
      await api.post(`/admin/questions/${question.id}/reject`, {
        reason: rejectionReason
      });
      toast.success('Question rejected');
      handleNext();
    } catch (error) {
      toast.error('Failed to reject question');
    }
  };

  const handleNext = () => {
    setReviewNotes('');
    setRejectionReason('');
    if (currentIndex < questions.length - 1) {
      setCurrentIndex(currentIndex + 1);
    } else {
      navigate(`/admin/assessments`);
    }
  };

  if (loading) {
    return <div className="p-6 text-center">Loading pending questions...</div>;
  }

  if (questions.length === 0) {
    return (
      <div className="p-6">
        <button
          onClick={() => navigate('/admin/assessments')}
          className="flex items-center gap-2 mb-6 text-indigo-600 hover:text-indigo-700"
        >
          <FiArrowLeft /> Back to Assessments
        </button>
        <div className="card text-center py-12">
          <p className="text-gray-600 text-lg">No pending questions to review</p>
          <p className="text-gray-500 text-sm mt-2">All questions have been reviewed</p>
        </div>
      </div>
    );
  }

  const currentQuestion = questions[currentIndex];
  const progress = ((currentIndex + 1) / questions.length) * 100;

  return (
    <div className="p-6">
      <button
        onClick={() => navigate('/admin/assessments')}
        className="flex items-center gap-2 mb-6 text-indigo-600 hover:text-indigo-700"
      >
        <FiArrowLeft /> Back to Assessments
      </button>

      <div className="mb-6">
        <h1 className="page-title">Review Generated Questions</h1>
        <p className="page-subtitle">Question {currentIndex + 1} of {questions.length}</p>
      </div>

      <div className="mb-4">
        <div className="flex justify-between text-sm text-gray-600 mb-2">
          <span>Progress</span>
          <span>{Math.round(progress)}%</span>
        </div>
        <div className="w-full bg-gray-200 rounded-full h-2">
          <div
            className="bg-indigo-600 h-2 rounded-full transition-all duration-300"
            style={{ width: `${progress}%` }}
          />
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
          <div className="card p-8">
            <div className="mb-4">
              <span className="inline-block px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm font-medium">
                {currentQuestion.moduleType}
              </span>
              <span className="ml-2 inline-block px-3 py-1 bg-yellow-100 text-yellow-700 rounded-full text-sm font-medium">
                {currentQuestion.cefrLevel}
              </span>
              <span className="ml-2 inline-block px-3 py-1 bg-orange-100 text-orange-700 rounded-full text-sm font-medium">
                Generated by {currentQuestion.generatedBy}
              </span>
            </div>

            <div className="my-6 p-6 bg-gray-50 rounded-lg border-l-4 border-indigo-600">
              <h3 className="font-bold text-lg mb-2">Question Text</h3>
              <p className="text-gray-800">{currentQuestion.questionText}</p>
            </div>

            {currentQuestion.options && currentQuestion.options.length > 0 && (
              <div className="mb-6">
                <h3 className="font-bold text-lg mb-3">Options</h3>
                <div className="space-y-2">
                  {currentQuestion.options.map((option, idx) => (
                    <div key={idx} className="p-3 bg-gray-100 rounded">
                      <span className="font-medium">{String.fromCharCode(65 + idx)}.</span> {option}
                    </div>
                  ))}
                </div>
                {currentQuestion.correctAnswer && (
                  <div className="mt-4 p-3 bg-green-50 border border-green-200 rounded">
                    <p className="text-green-800">
                      <strong>Correct Answer:</strong> {currentQuestion.correctAnswer}
                    </p>
                  </div>
                )}
              </div>
            )}

            {currentQuestion.explanation && (
              <div className="mb-6 p-4 bg-blue-50 border border-blue-200 rounded">
                <h3 className="font-bold text-sm mb-2">Explanation</h3>
                <p className="text-sm text-gray-700">{currentQuestion.explanation}</p>
              </div>
            )}

            {currentQuestion.audioUrl && (
              <div className="mb-6">
                <h3 className="font-bold text-lg mb-2">Audio Content</h3>
                <audio src={currentQuestion.audioUrl} controls className="w-full" />
              </div>
            )}

            {currentQuestion.imageUrl && (
              <div className="mb-6">
                <h3 className="font-bold text-lg mb-2">Image Content</h3>
                <img src={currentQuestion.imageUrl} alt="Question content" className="max-w-full rounded" />
              </div>
            )}

            <div className="mb-6">
              <label className="block font-medium mb-2">Review Notes (Optional)</label>
              <textarea
                value={reviewNotes}
                onChange={(e) => setReviewNotes(e.target.value)}
                placeholder="Add any notes or feedback about this question..."
                className="form-input min-h-24"
              />
            </div>
          </div>
        </div>

        <div className="lg:col-span-1">
          <div className="card p-6 sticky top-6">
            <h3 className="font-bold text-lg mb-4">Review Actions</h3>

            <button
              onClick={handleApprove}
              className="w-full flex items-center justify-center gap-2 px-4 py-3 mb-3 bg-green-600 text-white rounded hover:bg-green-700 font-medium"
            >
              <FiCheck size={18} />
              Approve Question
            </button>

            <div className="border-t my-4"></div>

            <label className="block text-sm font-medium mb-2">Rejection Reason (if rejecting)</label>
            <textarea
              value={rejectionReason}
              onChange={(e) => setRejectionReason(e.target.value)}
              placeholder="Explain why this question should be rejected..."
              className="form-input min-h-24 text-sm mb-3"
            />

            <button
              onClick={handleReject}
              className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-red-600 text-white rounded hover:bg-red-700 font-medium"
            >
              <FiX size={18} />
              Reject Question
            </button>

            {currentIndex < questions.length - 1 && (
              <button
                onClick={handleNext}
                className="w-full mt-4 flex items-center justify-center gap-2 px-4 py-2 bg-gray-300 text-gray-700 rounded hover:bg-gray-400"
              >
                <FiArrowLeft size={16} />
                Skip to Next
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default QuestionReview;
